#!/usr/bin/perl
use Graphics::Libplot ':ALL';

# type of plotting device
$device = 'X';
if (@ARGV) {
    $device = $ARGV[0];	
    die "Uknown device: $ARGV[0]" unless $ARGV[0] =~ /^ps|X|fig$/;
}

$SIZE=100.0;
$EXPAND = 2.2;
$M_PI= 3.14159265358979;
#       /* set a Plotter parameter */
       parampl("PAGESIZE", "letter");
#       /* create a Postscript Plotter that writes to standard output */
       parampl ("BITMAPSIZE", "500x500");
       if (($handle = newpl ($device, stdin, stdout, stderr)) < 0)
         {
           die "Couldn't create Plotter";
         }
       selectpl ($handle);    #        /* select the Plotter for use */
     
       if (openpl () < 0)      #      /* open Plotter */
         {
           die "Couldn't open Plotter";
         }
       fspace (-($SIZE), -($SIZE), $SIZE, $SIZE); #/* specify user coor system */
       pencolorname ("blue");       # /* pen color will be blue */
       fillcolorname ("white");
       filltype (1);               #  /* ellipses will be filled with white */
#       fontname ("NewCenturySchlbk-Roman");#  /* choose a Postscript font */
#       fontname ("utopia-medium-r-normal");#  /* choose a Postscript font */
       fontname ("HersheySerif");#  /* choose a Postscript font */
{
       my $i;     
       for ($i = 80; $i > 1; $i--)   #   /* loop through angles */
         {
           $theta = 0.5 * $i; # /* theta is in radians */
           $radius = $SIZE / ($theta**(0.35));  #/* this yields a spiral */
           fmove($radius * cos($theta), $radius * sin($theta));
           draw_boxed_string("GNU libplot!", 0.04 * $radius,(180.0*$theta / $M_PI) - 90.0);
         }
 }    
       if (closepl () < 0)       #    /* close Plotter */
         {
	     die "Couldn't close Plotter";
         }
       selectpl (0);
       if (deletepl ($handle) < 0) #   /* delete Plotter we used */
         {
           die "Couldn't delete Plotter";
         }

sub draw_boxed_string
{
    my ($s,$size,$angle) = @_;
    my ($true_size,$width);
    ftextangle($angle);             #/* text inclination angle (degrees) */
    $true_size = ffontsize($size);  #/* choose font size */
    $width = flabelwidth($s);       #/* compute width of text string */
    fellipserel (0.0, 0.0, $EXPAND * 0.5 * $width, $EXPAND * 0.5 * $true_size, $angle);
    alabel (ord 'c', ord 'c', $s);  #/* draw centered text string */
}

1; #OK
